name: Documentation

on:
  push:
    branches: [ main, master ]
  release:
    types: [created]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
      - uses: actions/checkout@v4

      - name: Set up python
      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          virtualenvs-create: true
          virtualenvs-in-project: true
          installer-parallel: true

      - name: Install dependencies
      - run: |
         python -m pip install --upgrade poetry
         poetry install --only dev
         
      - name: Deploy docs dependencies
      - run: 
          - run: |
            source .venv/bin/activate
            mkdocs gh-deploy --force
